<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumne [
  <!ELEMENT alumne (nom, cognom, telefon?, email?, modul+)>
  <!ELEMENT nom (#PCDATA)>
  <!ELEMENT cognom (#PCDATA)>
  <!ELEMENT telefon (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT modul (#PCDATA)>
  <!ATTLIST alumne id CDATA #REQUIRED
                   tipus (presencial | distancia) #REQUIRED>
]>
<alumne id="A001" tipus="presencial">
  <nom>Maria</nom>
  <cognom>Garcia</cognom>
  <telefon>612345678</telefon>
  <email>maria.garcia@exemple.com</email>
  <modul>Llenguatge de marques</modul>
  <modul>Bases de dades</modul>
</alumne>